### ISSUE TITLE
AnnotatedSpectra or MatchedSpectra

### ISSUE THREAD

**Issue by jorainer** [michaelwitting/MetaboAnnotation#1]
Object representing matches between experimental and reference spectra.

The data we have is:
- `Spectra` representing the experimental spectra
- `Spectra` representing the database/reference matches
- mapping between these two including a similarity score.

One possibility to represent this would be:

```r
setClass(
    "MatchedSpectra",
    slots = c(
        query = "Spectra",
        target = "Spectra",
        matches = "data.frame",
        ## metadata
        metadata = "list",
        version = "character"
    ),
    prototype = prototype(version = "0.1")
)
```

`matches` would be a `data.frame` with columns `query_idx`, `target_idx` and `score` to establish the n:m mapping between `@query` and `@target`.

Accessing spectra variables can be tricky because they are duplicated. A possibility would be to require a prefix `"query_"` or `"target_"` on them. Or use then *as is* for `query` and require a prefix to extract them from the `target`.

`spectraData` would then extract the combined information from both spectra.

Open questions:
1) too complicated to subset and work with it?
2) do we expect additional operations performed on this object?

**Comment by jorainer** [comment]
Happy for feedback @michaelwitting , but also @lgatto, whether something similar would be interesting for the proteomics world

**Comment by michaelwitting** [comment]
I was originally thinking about `data.frame` that would be attached to the query spectrum. Tricky task. The function I had in mind would return a `list` of `data.frame` of the same length as the input `Spectra`.

You said you can attached a `Spectra` to `Spectra`, meaning via `$` right?

**Comment by lgatto** [comment]
It would be useful to define a set of use cases. Here's a use case for proteomics MS2 spectra:

```r
> PSM::calculateFragments("VESITARHGEVLQLRPK")
Modifications used: C=57.02146
          mz ion type pos z              seq
1   100.0757  b1    b   1 1                V
2   229.1183  b2    b   2 1               VE
3   316.1503  b3    b   3 1              VES
4   429.2344  b4    b   4 1             VESI
5   530.2820  b5    b   5 1            VESIT
6   601.3192  b6    b   6 1           VESITA
7   757.4203  b7    b   7 1          VESITAR
8   894.4792  b8    b   8 1         VESITARH
9   951.5006  b9    b   9 1        VESITARHG
10 1080.5432 b10    b  10 1       VESITARHGE
11 1179.6116 b11    b  11 1      VESITARHGEV
12 1292.6957 b12    b  12 1     VESITARHGEVL
13 1420.7543 b13    b  13 1    VESITARHGEVLQ
14 1533.8383 b14    b  14 1   VESITARHGEVLQL
15 1689.9394 b15    b  15 1  VESITARHGEVLQLR
16 1786.9922 b16    b  16 1 VESITARHGEVLQLRP
```
I will need to read @jorainer's suggestion above, but we need to think about what we want to store in such annotations: only the peak annotations or more information (such as query and target scans, ...), which might be more related to the computation rather than the actual results/annotations.

**Comment by jorainer** [comment]
What I propose here is exclusively representing matching results between two `Spectra`.

The use case for me would be the following:
- I have experimental MS2 spectra in a `Spectra` object `a` that are related to a MS1 feature (I have then a `$feature_id` spectra variable in `a`).
- On the other hand I have a *reference* spectra (with MS2 spectra from e.g. MassBank) against which I want to match my spectra in `a`.
- Then I'm matching the spectra in `a` to the ones from the reference and I record which spectra in the reference have a high similarity (e.g. > 0.8).

As a result we get a n:m mapping between `a` and the reference. Each spectrum in `a` can map 0:n spectra in the reference and a spectra in reference can map to 0:m spectra in `a`.

To *represent/store* this result we could either:
- have the matching spectra from the reference added as a spectra variable of `a`.
- keep the matching spectra together in a new result object

The first one would be easy to implement, but I see there some problems because of the nested structure.

For the second approach, I would store the full query spectra `a` in the slot `@query` and the subset of spectra from reference (let's call it `b`) that match at least on query spectrum in the slot `@target`. The `@mapping` represents then the n:m mapping matrix, one row for one match of query to reference, with the index of the spectrum in `a`, the index of the spectrum in `b` and the score for that.

I know it sounds complicated, but I would like to have all data together - which would then maybe also simplify exporting the result.

**Comment by michaelwitting** [comment]
For the second approach, the length of the result would equal to the length of `a`. In case of no results found `@target` and `@mapping` would be empty, right?
If I want the the result for a specific index, e.g. `a[100]` then I would call `resultObject[100]`?

**Comment by lgatto** [comment]
Ok, so what you are after is not really the annotation of spectra but matching spectra. You want to formalise the downstream results from `compareSpectra()`. 

I would strongly oppose to your first solution. Spectra should not be added as `spectraVariables`.

If we try to simplify things, your results could be stored as a matrix or list of hits. With these indices, it would be very easy to extract the relevant query and target spectra. I suppose that copying them in a new data structure isn't an issue as long as the raw data is stored externally. 

It would also be useful to hear about the pipeline you envision. Would it be a single function that takes your query and target `Spectra` objects and a distance threshold and return such a `MatchedSpectra` object? Are the distances and threshold between spectra a done deal? Because otherwise, these are some aspects that would be important to control and visualise, for example using a heatmap on the `compareSpectra()` output.

(by the way, we use `ListorHits` class in QFeatures to record mappings across quantitative feature levels)

**Comment by michaelwitting** [comment]
For the whole thing is about convenience. I'm doing all my MS2 matching within R. At the moment I'm storing all results in a `data.frame` and I'm linking results to query spectra and library spectra via IDs.
What I could imagine is a plotting function for `MatchedSpectra` creating all mirror plots for all results.

**Comment by jorainer** [comment]
As Michael said, we have a set of MS2 spectra and we usually match that against a reference database. What I would suggest is to represent this mapping/matching in a `data.frame` with the indices to the query and target spectra. This would be the `@matches` slot of the object. I would just also save the spectra into the same object so that re-ordering, subsetting etc is more convenient - or plotting etc.

The whole workflow would look like:

```r
## xdata is an XCMSnExp object and this function returns all 
## MS2 spectra for features in that
sps <- featureSpectra(xdata) 

## this function uses compareSpectra to compare the spectra 
## and builds the result object, i.e. the MatchedSpectra
res <- matchSpectra(sps, massbank, threshold = 0.7, ...) 
```

**Comment by lgatto** [comment]
I am doing some work with spectra clustering at the moment. As far as I can see, there are a lot of open issues (distances, parameters, thresholds) - and hiding everything in a function isn't ideal in my opinion. I think it would be useful, for the future, to make different steps and intermediate visualisations explicit, even if a single wrapper runs everything in one go.

**Comment by jorainer** [comment]
I agree, but with `Spectra` we have all the necessary tools for *power users* to do this kind of comparisons. For more *standard* workflows (identifying the best matches against a reference) I would like to have a high-level function that simplifies that for the *normal user*. The function will however be as modular and configurable as possible.

**Comment by stanstrup** [comment]
Wouldn't keeping results in a matrix be easier to subset?
You could have a function `matches` that optionally returns indexes.
It would be convenient if the object also kept track of how the matching was done.
Subsetting based on the scores in matches would also be convenient.

```r
setClass(
    "MatchedSpectra",
    slots = c(
        query = "Spectra",
        target = "Spectra",
        matches = "matrix",
        match_fun = "character",
        match_param = "list",
        ## metadata
        metadata = "list",
        version = "character"
    ),
    prototype = prototype(version = "0.1")
)
```

**Comment by michaelwitting** [comment]
What I'm still missing (and maybe that is my ignorance, lack of knowledge, etc): How "long" would this object be? If I have 100 `Spectra` I'm matching against a library of `Spectra` the `MatchedSpectra` would also have the length 100? If I want to know the matching results of the original `Spectra[50]` would I call `MatchedSpectra[50]`?

**Comment by jorainer** [comment]
@stanstrup, there's no big difference between having it as a `data.frame` or `matrix`, only that accessing columns in a `data.frame` is slightly faster.

@michaelwitting initially yes, it will have length 100, but I intend to implement also functions that allow to *prune* that. And yes, `MatchedSpectra[50]` will return you (all) the matches of query spectrum 50. I'm working on it and once I have a prototype ready I'll let you know.

**Comment by stanstrup** [comment]
@jorainer my point was not about the data type but if to store indexes or the comparison matrix from `compareSpectra`. If you keep it as the length(a):length(b) matrix I imagine subsetting is easier as you don't have to re-calculate indexes.
You could also easier have an object where you could subset in two dimensions.
`MatchedSpectra[c(1:3), c(7:9)] ` could return the 3 first query spectra with the 7:9 reference spectra.

**Comment by jorainer** [comment]
The `MatchedSpectra` object in its current implementation is thought to *just* contain the matching spectra (thus keeping only the indices). I don't really see the point/need to keep the full correlation matrix - if you want to do that you could simply keep the matrix you get from `compareSpectra`. The other point is that I don't want to do an all against all comparison at present (the correlation matrix will be huge and we can easily run out of memory (unless we start using sparse matrices)).

**Comment by michaelwitting** [comment]
I checked the first implementation and it looks good to me. I will search for some good data for a vignette.
One minor point: Can we have a column `matchFun` in the `matches` data.frame? I think this suggestion by @stanstrup was very good.

**Comment by michaelwitting** [comment]
Is it supposed to also handle multipe matching functions? For example doing a forward and reverse dot product and storing both results in the same data frame?

**Comment by michaelwitting** [comment]
Example:
`matches$query_id   matches$target_idx   matches$score   matches$matchFun`
`1                              1                                 0.73                    forwardDp`
`1                              1                                 0.85                    reverseDp`

**Comment by michaelwitting** [comment]
> As Michael said, we have a set of MS2 spectra and we usually match that against a reference database. What I would suggest is to represent this mapping/matching in a `data.frame` with the indices to the query and target spectra. This would be the `@matches` slot of the object. I would just also save the spectra into the same object so that re-ordering, subsetting etc is more convenient - or plotting etc.
> 
> The whole workflow would look like:
> 
> ```r
> ## xdata is an XCMSnExp object and this function returns all 
> ## MS2 spectra for features in that
> sps <- featureSpectra(xdata) 
> 
> ## this function uses compareSpectra to compare the spectra 
> ## and builds the result object, i.e. the MatchedSpectra
> res <- matchSpectra(sps, massbank, threshold = 0.7, ...) 
> ```

Shall the treshold be in this function or shall we have an additional function `treshold` that works on a `MatchedSpectra`?

**Comment by jorainer** [comment]
Closing this issue now as the `MatchedSpectra` object and the `matchSpectra` function are implemented. I'm currently trying the functionality *in the wild* (i.e. using it in the annotation process) - if something is not working in its current implementation I will re-open the issue.
