### ISSUE TITLE
Mass and m/z matching

### ISSUE THREAD

**Issue by jorainer** [michaelwitting/MetaboAnnotation#2]
This would be a simple MS1-only annotation using the m/z of e.g. a feature to a compound database (with masses). This could help identifying some first exhaustive list of candidates.

I would suggest to implement that in a modular way:

```r
match_mass_mass <- function(x, y, ppm = 5, tolerance = 0) {
    ## match x and y with closest - note that ppm on the mass instead of the m/z might not be ideal
}

match_mz_mass <- function(x, y, adduct = c("[M+H]+", "[M+Na]+"), ppm = 5, tolerance = 0) {
    ## convert the mz x into mass x
    x_mass <- mz2mass(x, adduct = adduct)
    ## call the match_mass_mass function with that.
}
```

these functions above should actually return a `list` of `integer` with which elements in `y` match `x`. There should then be higher level methods that work on `data.frame` or then also `CompDb` databases. Something along:

```r
setMethod("matchMz", signature = c(x = "data.frame", y = "data.frame"))
setMethod("matchMz", signature = c(x = "data.frame", y = "CompDb"))
...
```

We would then have to decide what should be returned as a result...

**Comment by michaelwitting** [comment]
Actually, I prefer to compare to compare m/z with m/z, especially for the case you mentioned with ppm error. Therefore I prefer to calculate the theoretical m/z values first and then match.
Along the same way: You normally compare the isotope pattern of ions against the theoretical isotope pattern of the ion. So in this regard I would do everything on m/z level.

**Comment by michaelwitting** [comment]
I can make it more modular with `setMethod()`, have to look it up how to do, but shouldn't be a problem.

**Comment by jorainer** [comment]
The reason for the mass instead of the m/z was that it would be computationally better to convert the input m/z values to masses (for all the specified adducts) instead of calculating m/z from all masses in the database...

**Comment by michaelwitting** [comment]
I know. This was also the reason, why in previous versions I used precalculated m/z values, but this time I would like to be flexible.

**Comment by jorainer** [comment]
We can get around this (I guess) - we can "translate" the ppm for an m/z into the `tolerance` and use that then in the comparison of masses. What I mean:

m/z value 132.3, ppm = 10, tolerance = 0 -> m/z value 132.3, ppm = 0, tolerance = 0.001323, convert the m/z to all possible masses and then use this mass (along with the tolerance) in the database comparison against the exact mass there

**Comment by michaelwitting** [comment]
I have the feeling that this is a bit of cheating... Just a gut feeling.
However, calculation of the ion m/z is only done once during the function call.
One million numbers with all positive mode adducts takes about 6 seconds on my PC.

**Comment by michaelwitting** [comment]
Sorry, 6 sec with display, 1.24 sec storing in object.

**Comment by jorainer** [comment]
OK, let's see how your implementation works and then see how/if we can tune it etc.

**Comment by michaelwitting** [comment]
Unit test for basic function is there. I check if I can find a example for checking performance.

**Comment by jorainer** [comment]
Closing this issue now, since the (updated) code is in PR #12 . If the implemented way (convert the target mass to m/z and then compare the m/z values) turns out to be too computationally intense we can also implement the other way round with a different *Param* object.
