### ISSUE TITLE
Comparison functions for spectral matching

### ISSUE THREAD

**Issue by michaelwitting** [michaelwitting/MetaboAnnotation#4]
I would like to implement a function called `compareLibrarySpectra` (working title). This function shall compare a `Spectra` `x` against `Spectra` `y`, where `x` are the query spectra and `y` the library spectra.
The function shall return a `MatchedSpectra` and perform spectral similarity comparison based on forward and reverse dot product (and maybe number of matching peaks).
My question to @jorainer: Is `compareSpectra` parallelized? Would it make sense to use `spectrapply` to speed up comparison?

**Comment by michaelwitting** [comment]
Library spectra shall be filtered by the `precursorMz` of `x` within `tolerance` / `ppm`.

**Comment by michaelwitting** [comment]
name would be `matchSpectra` according to @jorainer (see #1).

**Comment by jorainer** [comment]
Wait, I have already implemented that method. It can be parallelized and it does prefilter - if wanted. I just need to finish the documentation and vignette on that and I will push and make a pull request.
